# Part of this code is based on https://github.com/Walter0807/MotionBERT
import torch
import torch.nn as nn
from torch.utils.checkpoint import checkpoint
import math
import warnings

from .rotary_embedding import ROPE


def drop_path(x, drop_prob: float = 0.0, training: bool = False):
    """Drop paths (Stochastic Depth) per sample (when applied in main path of residual blocks).
    This is the same as the DropConnect impl I created for EfficientNet, etc networks, however,
    the original name is misleading as 'Drop Connect' is a different form of dropout in a separate paper...
    See discussion: https://github.com/tensorflow/tpu/issues/494#issuecomment-532968956 ... I've opted for
    changing the layer and argument names to 'drop path' rather than mix DropConnect as a layer name and use
    'survival rate' as the argument.
    """
    if drop_prob == 0.0 or not training:
        return x
    keep_prob = 1 - drop_prob
    shape = (x.shape[0],) + (1,) * (
        x.ndim - 1
    )  # work with diff dim tensors, not just 2D ConvNets
    random_tensor = keep_prob + torch.rand(shape, dtype=x.dtype, device=x.device)
    random_tensor.floor_()  # binarize
    output = x.div(keep_prob) * random_tensor
    return output


class DropPath(nn.Module):
    """Drop paths (Stochastic Depth) per sample  (when applied in main path of residual blocks)."""

    def __init__(self, drop_prob=None):
        super(DropPath, self).__init__()
        self.drop_prob = drop_prob

    def forward(self, x):
        return drop_path(x, self.drop_prob, self.training)


def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1.0 + math.erf(x / math.sqrt(2.0))) / 2.0

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn(
            "mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
            "The distribution of values may be incorrect.",
            stacklevel=2,
        )

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.0))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def trunc_normal_(tensor, mean=0.0, std=1.0, a=-2.0, b=2.0):
    # type: (torch.Tensor, float, float, float, float) -> torch.Tensor
    r"""Fills the input Tensor with values drawn from a truncated
    normal distribution. The values are effectively drawn from the
    normal distribution :math:`\mathcal{N}(\text{mean}, \text{std}^2)`
    with values outside :math:`[a, b]` redrawn until they are within
    the bounds. The method used for generating the random values works
    best when :math:`a \leq \text{mean} \leq b`.
    Args:
        tensor: an n-dimensional `torch.Tensor`
        mean: the mean of the normal distribution
        std: the standard deviation of the normal distribution
        a: the minimum cutoff value
        b: the maximum cutoff value
    Examples:
        >>> w = torch.empty(3, 5)
        >>> nn.init.trunc_normal_(w)
    """
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)


class MLP(nn.Module):
    def __init__(
        self,
        in_features,
        hidden_features=None,
        out_features=None,
        act_layer=nn.GELU,
        drop=0.0,
    ):
        super().__init__()
        out_features = out_features or in_features
        hidden_features = hidden_features or in_features
        self.fc1 = nn.Linear(in_features, hidden_features)
        self.act = act_layer()
        self.fc2 = nn.Linear(hidden_features, out_features)
        self.drop = nn.Dropout(drop)

    def forward(self, x):
        x = self.fc1(x)
        x = self.act(x)
        x = self.drop(x)
        x = self.fc2(x)
        x = self.drop(x)
        return x


class Attention(nn.Module):
    def __init__(
        self,
        cfg,
        dim,
        st_mode="temporal",
    ):
        super().__init__()

        num_heads = cfg.num_heads
        qkv_bias = cfg.get("qkv_bias", True)
        qk_scale = cfg.get("qk_scale", None)
        proj_drop = cfg.get("drop_rate", 0.0)
        attn_drop = cfg.get("attn_drop_rate", 0.0)

        self.num_heads = num_heads
        head_dim = dim // num_heads
        self.head_dim = head_dim
        self.scale = qk_scale or head_dim**-0.5

        self.attn_drop = nn.Dropout(attn_drop)
        self.proj = nn.Linear(dim, dim)
        self.mode = st_mode
        self.qkv = nn.Linear(dim, dim * 3, bias=qkv_bias)
        self.proj_drop = nn.Dropout(proj_drop)

        if self.mode == "temporal":
            self.rope = ROPE(head_dim)
            self.attn_len = cfg.get("attn_len", 60)

    def forward(self, x, key_padding_mask=None):
        B, F, J, C = x.shape

        if self.mode == "temporal":
            if key_padding_mask is not None:
                key_padding_mask = key_padding_mask[:, None, :].expand(-1, J, -1).reshape(B * J, F)
            x = x.permute(0, 2, 1, 3).reshape(B * J, F, C)
            qkv = (
                self.qkv(x)
                .reshape(-1, F, 3, self.num_heads, C // self.num_heads)
                .permute(2, 0, 3, 1, 4)
            )
            q, k, v = (
                qkv[0],
                qkv[1],
                qkv[2],
            )  # make torchscript happy (cannot use tensor as tuple)
            
            # Apply RoPE to queries and keys
            q = self.rope.rotate_queries_or_keys(q)  # B*J, N, F, C
            k = self.rope.rotate_queries_or_keys(k)  # B*J, N, F, C
            
            x = self.forward_attention(q, k, v, key_padding_mask=key_padding_mask)
            x = x.reshape(B, J, F, C).permute(0, 2, 1, 3)
        elif self.mode == "spatial":
            x = x.reshape(B * F, J, C)
            qkv = (
                self.qkv(x)
                .reshape(-1, J, 3, self.num_heads, C // self.num_heads)
                .permute(2, 0, 3, 1, 4)
            )
            q, k, v = (
                qkv[0],
                qkv[1],
                qkv[2],
            )  # make torchscript happy (cannot use tensor as tuple)
            x = self.forward_attention(q, k, v)
            x = x.reshape(B, F, J, C)
        else:
            raise NotImplementedError(self.mode)
        x = self.proj(x)
        x = self.proj_drop(x)
        return x

    def forward_attention(self, q, k, v, key_padding_mask=None):
        B, H, N, C = q.shape
        attn = (q @ k.transpose(-2, -1)) * self.scale

        if self.mode == "temporal":
            # Create attention mask based on attn_len
            # Each frame i can only attend to frames [i-attn_len, i+attn_len]
            attn_mask = torch.zeros(N, N, dtype=torch.bool, device=q.device)
            for i in range(N):
                start = max(0, i - self.attn_len)
                end = min(N, i + self.attn_len + 1)
                attn_mask[i, start:end] = True
            
            attn_mask = attn_mask.reshape(1, 1, N, N).expand(B, H, -1, -1)
            attn = attn.masked_fill(attn_mask.logical_not(), float("-inf"))

        if key_padding_mask is not None:
            key_padding_mask = key_padding_mask.reshape(B, 1, 1, N).expand(-1, H, N, -1)
            attn = attn.masked_fill(key_padding_mask, float("-inf"))

        attn = attn.softmax(dim=-1)

        attn = self.attn_drop(attn)

        x = attn @ v
        x = x.transpose(1, 2).reshape(B, N, C * self.num_heads)
        return x


class Block(nn.Module):

    def __init__(
        self,
        cfg,
        # dimensions
        dim,
        # other configs
        drop_path=0.0,
        mlp_out_ratio=1.0,
        act_layer=nn.GELU,
        norm_layer=nn.LayerNorm,
        st_mode="stage_st",
        att_fuse=False,
    ):
        super().__init__()
        self.cfg = cfg
        mlp_ratio = cfg.get("mlp_ratio", 4)
        drop = cfg.get("drop_rate", 0.0)

        self.st_mode = st_mode

        self.norm1_s = norm_layer(dim)
        self.norm1_t = norm_layer(dim)
        self.attn_s = Attention(
            cfg,
            dim,
            st_mode="spatial",
        )
        self.attn_t = Attention(
            cfg,
            dim,
            st_mode="temporal",
        )

        # NOTE: drop path for stochastic depth, we shall see if this is better than dropout here
        self.drop_path = DropPath(drop_path) if drop_path > 0.0 else nn.Identity()
        self.norm2_s = norm_layer(dim)
        self.norm2_t = norm_layer(dim)
        mlp_hidden_dim = int(dim * mlp_ratio)
        mlp_out_dim = int(dim * mlp_out_ratio)
        self.mlp_s = MLP(
            in_features=dim,
            hidden_features=mlp_hidden_dim,
            out_features=mlp_out_dim,
            act_layer=act_layer,
            drop=drop,
        )
        self.mlp_t = MLP(
            in_features=dim,
            hidden_features=mlp_hidden_dim,
            out_features=mlp_out_dim,
            act_layer=act_layer,
            drop=drop,
        )
        self.att_fuse = att_fuse
        if self.att_fuse:
            self.ts_attn = nn.Linear(dim * 2, dim * 2)

    def forward(self, x, key_padding_mask=None):
        if self.st_mode == "stage_st":
            x = x + self.drop_path(self.attn_s(self.norm1_s(x)))
            x = x + self.drop_path(self.mlp_s(self.norm2_s(x)))
            x = x + self.drop_path(self.attn_t(self.norm1_t(x), key_padding_mask=key_padding_mask))
            x = x + self.drop_path(self.mlp_t(self.norm2_t(x)))
        elif self.st_mode == "stage_ts":
            x = x + self.drop_path(self.attn_t(self.norm1_t(x), key_padding_mask=key_padding_mask))
            x = x + self.drop_path(self.mlp_t(self.norm2_t(x)))
            x = x + self.drop_path(self.attn_s(self.norm1_s(x)))
            x = x + self.drop_path(self.mlp_s(self.norm2_s(x)))
        elif self.st_mode == "stage_para":
            x_t = x + self.drop_path(self.attn_t(self.norm1_t(x), key_padding_mask=key_padding_mask))
            x_t = x_t + self.drop_path(self.mlp_t(self.norm2_t(x_t)))
            x_s = x + self.drop_path(self.attn_s(self.norm1_s(x)))
            x_s = x_s + self.drop_path(self.mlp_s(self.norm2_s(x_s)))
            if self.att_fuse:
                #             x_s, x_t: [B, F, J, C]
                B, F, J, C = x_s.shape
                alpha = torch.cat([x_s, x_t], dim=-1)
                alpha = self.ts_attn(alpha).reshape(B, F, J, C, 2)
                alpha = alpha.softmax(dim=-1)
                x = x_t * alpha[..., 1] + x_s * alpha[..., 0]
            else:
                x = (x_s + x_t) * 0.5
        else:
            raise NotImplementedError(self.st_mode)
        return x

class DSTFormer(nn.Module):
    def __init__(self, cfg, dim_feat, depth):
        super().__init__()
        self.cfg = cfg

        self.dim_feat = dim_feat
        self.depth = depth

        self.num_heads = cfg.num_heads
        self.mlp_ratio = cfg.mlp_ratio
        self.qkv_bias = cfg.get("qkv_bias", True)
        self.qk_scale = cfg.get("qk_scale", None)
        self.drop_rate = cfg.get("drop_rate", 0.0)
        self.attn_drop_rate = cfg.get("attn_drop_rate", 0.0)

        self.att_fuse = cfg.get("att_fuse", True)

        self.blocks_st = nn.ModuleList(
            [
                Block(
                    self.cfg,
                    dim=self.dim_feat,
                    st_mode="stage_st",
                )
                for i in range(self.depth)
            ]
        )
        self.blocks_ts = nn.ModuleList(
            [
                Block(
                    self.cfg,
                    dim=self.dim_feat,
                    st_mode="stage_ts",
                )
                for i in range(self.depth)
            ]
        )

        if self.att_fuse:
            self.ts_attn = nn.ModuleList(
                [nn.Linear(self.dim_feat * 2, 2) for i in range(self.depth)]
            )
            for i in range(self.depth):
                self.ts_attn[i].weight.data.fill_(0)
                self.ts_attn[i].bias.data.fill_(0.5)

    def forward(self, x, key_padding_mask=None):
        for idx, (blk_st, blk_ts) in enumerate(zip(self.blocks_st, self.blocks_ts)):
            if self.training:
                x_st = checkpoint(
                    blk_st,
                    x,
                    key_padding_mask=key_padding_mask,
                    use_reentrant=False,
                    preserve_rng_state=True,
                )
                x_ts = checkpoint(
                    blk_ts,
                    x,
                    key_padding_mask=key_padding_mask,
                    use_reentrant=False,
                    preserve_rng_state=True,
                )
            else:
                x_st = blk_st(x, key_padding_mask=key_padding_mask)
                x_ts = blk_ts(x, key_padding_mask=key_padding_mask)
            if self.att_fuse:
                att = self.ts_attn[idx]
                alpha = torch.cat([x_st, x_ts], dim=-1)
                alpha = att(alpha)
                alpha = alpha.softmax(dim=-1)
                x = x_st * alpha[..., 0:1] + x_ts * alpha[..., 1:2]
            else:
                x = (x_st + x_ts) * 0.5
        return x

